### ISSUE TITLE
[BUG]Run the code of the emample but failed

### ISSUE THREAD

**Issue by CarrieBishop** [trevorld/ggpattern#109]
**Bug description**

I download "ggpattern" with the command `remotes::install_github("coolbutuseless/ggpattern")
` ,and download the package successfully.But I run the code in example failed.

```
library("ggplot2")
library("ggpattern")
df <- data.frame(level = c("a", "b", "c", 'd'), outcome = c(2.3, 1.9, 3.2, 1))

ggplot(df) +
  geom_col_pattern(
    aes(level, outcome, pattern_fill = level), 
    pattern = 'stripe',
    fill    = 'white',
    colour  = 'black'
  ) +
  theme_bw(18) +
  theme(legend.position = 'none') + 
  labs(
    title    = "ggpattern::geom_col_pattern()",
    subtitle = "pattern = 'stripe'"
  ) +
  coord_fixed(ratio = 1/2)
```

**Session info**
The output in RStudio are following:
`Error:  when calculate 'units' in loadNamespace().onLoad failed，details：
  call: NULL
  error: no database found!`

Can you tell me how to solve the problem?

**Comment by trevorld** [comment]
* You code example works for me (when tweaked to remove the extraneous markdown and missing `library()` calls) 
* Does `library("units")` work for you?  `{units}` is a package I think `{ggplot2}` depends on?  Maybe your installation is messed up?  If so this isn't something I could help you with.
* You could provide your `sessionInfo()` output but since this seems unlikely to be a bug in `{ggpattern}` itself I'm closing the issue for now.  Note the error message you see isn't being thrown by `{ggpattern}` itself but something lower-level.  If you set `options(error=recover())` you may be able to see where and what is throwing the error...
