### ISSUE TITLE
ggpattern website still relates to version 0.4.3-1

### ISSUE THREAD

**Issue by mpjashby** [trevorld/ggpattern#98]
The [ggpattern package website](https://coolbutuseless.github.io/package/ggpattern/) still refers to version 0.4.3-1. I'm not sure how much of a difference this makes in terms of the content, but e.g. the home page only gives instructions for installation from GitHub, not CRAN.

**Comment by trevorld** [comment]
> I'm not sure how much of a difference this makes in terms of the content

There isn't much difference in content between version 0.4.3-1 and 1.0.1 so I didn't feel it was worth asking @coolbutuseless to manually re-build the package website.

> the home page only gives instructions for installation from GitHub, not CRAN.

The current README still only gives instructions for installation from Github.  This wouldn't be changed by re-building the package website...  

Due to CRAN size limitations the CRAN version has less vignette documentation than the Github version.  I'm not entirely sure we should be recommending that they install the CRAN version but I guess we could add such instructions.
